config/routes.rb
Rails.application.routes.draw do
  root 'home#welcome', as: 'home'
  get '/info', to: 'home#info'
  resources :users do
    resources :courses do
      resources :standards
      resources :exams do
        resources :questions
      end
      resources :sections do
        resources :students
      end
    end
  end
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/user/:user_id/courses/:course_id/exams/:exam_id/publish', to: 'exams#publish', as: 'publish_user_course_exam'
  post '/user/:user_id/courses/:course_id/exams/:exam_id/scramble', to: 'exams#scramble', as: 'scramble_user_course_exam'
  put '/users/:user_id/courses/:course_id/sections/:section_id/students/:student_id/student_skill/:id', to: 'student_skills#increment', as: 'increment'
  patch '/users/:user_id/courses/:course_id/sections/:section_id/students/:student_id/student_skill/:id', to: 'student_skills#decrement', as: 'decrement'
  
end

app/models/student.rb
class Student < ApplicationRecord
  validates :name, presence: true
  validates :section_id, presence: true
  belongs_to :section
  has_many :student_skills, foreign_key: :student_id, dependent: :destroy
  
  def course
    section.course
  end
  
  def teacher
    course.user
  end
  
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  
  def new
    @course = Course.find_by(id: params[:course_id])
  end
    
  def create
    @course = Course.find_by(id: params[:course_id])
    if params[:student][:name].blank?
      flash.now[:error] = ["Name can't be blank"]
      render 'new'
    else
    params[:student][:name].split("\n").each do |name|
    @student = Student.create({name: name.strip, section_id: params[:section_id]})
     if @student.save and @student.course.standards.any?
      @student.course.standards.each do |standard|
        StudentSkill.create({student_id: @student.id, standard_id: standard.id, skill: 3 })
      end
     end
    end
    redirect_to user_course_sections_path(user_id: params[:user_id], course_id: params[:course_id])
    end
  end
  
  def destroy
    Student.find_by(id: params[:id]).destroy
    redirect_to user_course_sections_path(user_id: params[:user_id], course_id: params[:course_id])
  end
  
  def show
    @student = Student.find_by(id: params[:id])
  end
  
  def edit
    @student = Student.find_by(id: params[:id])
  end
  
  def update
    @student = Student.find_by(id: params[:id])
    if @student.update(name: params[:student][:name])
      redirect_to user_course_sections_path(user_id: current_user.id, course_id: @student.course.id)
    else
      flash.now[:error] = @student.errors.full_messages
      render 'edit'
    end
  end
  
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/edit.html.erb
<%= render "shared/edit", {obj: :student, url: user_course_section_student_path(user_id: current_user.id, course_id: @student.course.id, section_id: @student.section.id, id: @student.id)} %>

<br></br>

<%= link_to "Return", user_course_sections_path(user_id: current_user.id, course_id: @student.course.id) %>

app/views/students/new.html.erb
<%= render "shared/form", {obj: :student, url: user_course_section_students_path} %>

<br></br>

<%= link_to "Return", user_course_sections_path(user_id: current_user.id, course_id: @course.id) %>

app/views/students/show.html.erb
<h1><%= @student.name %></h1>

<br>

<h2>Skills
<% sorted_skills = @student.student_skills.sort_by {|ss| ss.standard.name } %>
<% sorted_skills.each do |skill| %>
<li><%= Standard.find_by(id: skill.standard_id).name %>: <%= skill.display %>
(<%= link_to "Add", increment_path(user_id: @student.teacher.id, course_id: @student.course.id, section_id: @student.section.id, student_id: @student.id, id: skill.id), method: :put %>,
<%= link_to "Subtract", decrement_path(user_id: @student.teacher.id, course_id: @student.course.id, section_id: @student.section.id, student_id: @student.id, id: skill.id), method: :patch %>)</li>
<% end %></h2>

<br>

<h2><%= link_to "Info", info_path %>, <%= link_to "Return", user_course_sections_path(user_id: @student.teacher.id, course_id: @student.course.id) %></h2> 