config/routes.rb
Rails.application.routes.draw do
  root 'home#welcome', as: 'home'
  get '/info', to: 'home#info'
  resources :users do
    resources :courses do
      resources :standards
      resources :exams do
        resources :questions
      end
      resources :sections do
        resources :students
      end
    end
  end
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/user/:user_id/courses/:course_id/exams/:exam_id/publish', to: 'exams#publish', as: 'publish_user_course_exam'
  post '/user/:user_id/courses/:course_id/exams/:exam_id/scramble', to: 'exams#scramble', as: 'scramble_user_course_exam'
  put '/users/:user_id/courses/:course_id/sections/:section_id/students/:student_id/student_skill/:id', to: 'student_skills#increment', as: 'increment'
  patch '/users/:user_id/courses/:course_id/sections/:section_id/students/:student_id/student_skill/:id', to: 'student_skills#decrement', as: 'decrement'
  
end

app/models/section.rb
class Section < ApplicationRecord
  belongs_to :course
  has_many :students, foreign_key: :section_id, dependent: :destroy
  validates :name, presence: true
  validates :course_id, presence: true
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  before_action :correct_user
  
  def new
    @course = Course.find_by(id: params[:course_id])
  end
  
  def create
    @course = Course.find_by(id: params[:course_id])
    if params[:section][:name].blank?
      flash.now[:error] = ["Name can't be blank"]
      render 'new'
    else
    params[:section][:name].split("\n").each do |name|
      @section = Section.create({name: name.strip, course_id: params[:course_id]})
    end
    redirect_to user_course_sections_path(user_id: params[:user_id], course_id: params[:course_id])
    end
  end
  
  
  def destroy
    Section.find_by(id: params[:id]).destroy
    redirect_to user_course_sections_path(user_id: params[:user_id], course_id: params[:course_id])
  end
  
  def index
  @course = Course.find_by(id: params[:course_id])
  end
  
  def edit
    @section = Section.find_by(id: params[:id])
  end
  
  def update
    @section = Section.find_by(id: params[:id])
    if @section.update(name: params[:section][:name])
      redirect_to user_course_sections_path(user_id: current_user.id, course_id: @section.course.id)
    else
      flash.now[:error] = @section.errors.full_messages
      render 'edit'
    end
  end
  
    
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/views/sections/edit.html.erb
<%= render "shared/edit", {obj: :section, url: user_course_section_path(user_id: current_user.id, course_id: @section.course.id, id: @section.id)} %>

<br></br>

<%= link_to "Return", user_course_sections_path(user_id: current_user.id, course_id: @section.course.id) %>

app/views/sections/index.html.erb
<h1><%= @course.name %> Sections (<%= link_to 'Add Sections', new_user_course_section_path(user_id: @course.user.id, course_id: @course.id) %>)</h1>

<br>
<% sorted_sections = @course.sections.sort_by {|s| s.name } %>
<% sorted_sections.each do |section| %>

<h2><%= section.name %> (<%= link_to 'Edit', edit_user_course_section_path(user_id: @course.user.id, course_id: @course.id, id: section.id) %>, <%= link_to "Delete", user_course_section_path(user_id: @course.user.id, course_id: @course.id, id: section.id), method: :delete %>)</h2>

<h3><%= section.students.count %> Students (<%= link_to "Add Students", new_user_course_section_student_path(user_id: @course.user.id, course_id: @course.id, section_id: section.id) %>)
<% sorted_students = section.students.sort_by {|s| s.name } %>
<% sorted_students.each do |student| %>
<li><%= student.name %> (<%= link_to 'Skills', user_course_section_student_path(user_id: @course.user.id, course_id: @course.id, section_id: student.section.id, id: student.id) %>, <%= link_to 'Edit', edit_user_course_section_student_path(user_id: @course.user.id, course_id: @course.id, section_id: section.id, id: student.id) %>, <%= link_to "Delete", user_course_section_student_path(user_id: @course.user.id, course_id: @course.id, section_id: section.id, id: student.id), method: :delete %>)
<% end %></li></h3>

<br>

<% end %>

<h2><%= link_to "Info", info_path %>,
<%= link_to "Return", user_courses_path(user_id: current_user.id) %></h2>

app/views/sections/new.html.erb
<%= render "shared/form", {obj: :section, url: user_course_sections_path} %>

<br></br>

<%= link_to "Return", user_course_sections_path(user_id: current_user.id, course_id: @course.id) %>