config/routes.rb
Rails.application.routes.draw do
  root 'home#welcome', as: 'home'
  get '/info', to: 'home#info'
  resources :users do
    resources :courses do
      resources :standards
      resources :exams do
        resources :questions
      end
      resources :sections do
        resources :students
      end
    end
  end
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/user/:user_id/courses/:course_id/exams/:exam_id/publish', to: 'exams#publish', as: 'publish_user_course_exam'
  post '/user/:user_id/courses/:course_id/exams/:exam_id/scramble', to: 'exams#scramble', as: 'scramble_user_course_exam'
  put '/users/:user_id/courses/:course_id/sections/:section_id/students/:student_id/student_skill/:id', to: 'student_skills#increment', as: 'increment'
  patch '/users/:user_id/courses/:course_id/sections/:section_id/students/:student_id/student_skill/:id', to: 'student_skills#decrement', as: 'decrement'
  
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :correct_user
  
  def new
  end
  
  def create
    if params[:course][:name].blank?
      flash.now[:error] = ["Name can't be blank"]
      render 'new'
    else
      params[:course][:name].split("\n").each do |name|
      @course = Course.create({name: name.strip, user_id: params[:user_id]})
      end
    redirect_to user_courses_path(user_id: params[:user_id])
    end
  end
  
  def destroy
    Course.find_by(id: params[:id]).destroy
    redirect_to user_courses_path(user_id: current_user.id)
  end
  
  def index
    @courses = current_user.courses
  end
  
  def edit
    @course = Course.find_by(id: params[:id])
  end
  
  def update
    @course = Course.find_by(id: params[:id])
    if @course.update(name: params[:course][:name])
      redirect_to user_courses_path(user_id: current_user.id)
    else
      flash.now[:error] = @course.errors.full_messages
      render 'edit'
    end
  end
    
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/edit.html.erb
<%= render "shared/edit", {obj: :course, url: user_course_path(user_id: current_user.id, id: @course.id)} %>

<br></br>

<%= link_to "Return", user_courses_path(user_id: current_user.id) %>

app/views/courses/index.html.erb
<h1><%= current_user.name %>'s Courses (<%= link_to "Add Courses", new_user_course_path(current_user) %>)</h1>

<br>
<% sorted_courses = current_user.courses.sort_by {|c| c.name } %>
<% sorted_courses.each do |course| %>
<h2><%= course.name %> 
(<%= link_to 'Exams', user_course_exams_path(user_id: current_user.id, course_id: course.id) %>, <%= link_to 'Sections', user_course_sections_path(user_id: current_user.id, course_id: course.id) %>, <%= link_to 'Edit', edit_user_course_path(user_id: current_user.id, id: course.id) %>, <%= link_to 'Delete', user_course_path(user_id: current_user.id, id: course.id), method: :delete %>)</h2>

<h3>Standards (<%= link_to 'Add Standards', new_user_course_standard_path(user_id: current_user.id, course_id: course.id) %>)
    <% sorted_standards = course.standards.sort_by {|s| s.name } %>
    <% sorted_standards.each do |standard| %>
    <li><%= standard.name %> (<%= link_to 'Edit', edit_user_course_standard_path(user_id: current_user.id, course_id: course.id, id: standard.id) %>, <%= link_to 'Delete', user_course_standard_path(user_id: current_user.id, course_id: course.id, id: standard.id), method: :delete %>)</li>
<% end %></h3>

<br>

<% end %>

<h2><%= link_to "Info", info_path %>,
    <%= link_to "Log Out", logout_path, method: :delete %></h2>

app/views/courses/new.html.erb
<%= render "shared/form", {obj: :course, url: user_courses_path} %>

<br></br>

<%= link_to "Return", user_courses_path(user_id: current_user.id) %>