config/routes.rb
Rails.application.routes.draw do
  root 'home#welcome', as: 'home'
  get '/info', to: 'home#info'
  resources :users do
    resources :courses do
      resources :standards
      resources :exams do
        resources :questions
      end
      resources :sections do
        resources :students
      end
    end
  end
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/user/:user_id/courses/:course_id/exams/:exam_id/publish', to: 'exams#publish', as: 'publish_user_course_exam'
  post '/user/:user_id/courses/:course_id/exams/:exam_id/scramble', to: 'exams#scramble', as: 'scramble_user_course_exam'
  put '/users/:user_id/courses/:course_id/sections/:section_id/students/:student_id/student_skill/:id', to: 'student_skills#increment', as: 'increment'
  patch '/users/:user_id/courses/:course_id/sections/:section_id/students/:student_id/student_skill/:id', to: 'student_skills#decrement', as: 'decrement'
  
end

app/models/exam.rb
class Exam < ApplicationRecord
  belongs_to :course
  has_many :questions, foreign_key: :exam_id, dependent: :destroy
  validates :name, presence: true
  validates :course_id, presence: true
  
  def author
    course.user
  end
  
  def recipients_hash
    rh = [['All students',1]]
    course.sections.each do |section|
      rh << [ section.name, section.id * 10 + 2 ]
    end
    course.sections.each do |section|
      section.students.each do |student|
        rh << [student.name, student.id * 10 + 3]
      end
    end
    rh
  end
  
  def scramble(idx, number_of_questions)
    students = recipients(idx)
    student_exams = []
    students.each do |student|
      student_exam = []
      student_exam << student.id
      pm = probability_matrix(student)
      uv = unique_select(pm, number_of_questions.to_i)
      student_exam << uv
      student_exams << student_exam
    end
    student_exams
  end
  
  def recipients(n)
    recipients = []
    case n[-1].to_i
    when 3
      recipients << Student.find_by(id: n[0..-2].to_i) 
    when 2
      Section.find_by(id: n[0..-2].to_i).students.each do |student|
        recipients << student
      end
    when 1
      course.sections.each do |section|
        section.students.each do |student|
          recipients << student
        end
      end
    end
    recipients
  end
  
  def probability(student_score, question_score)
    (6 - student_score)*(5 - (student_score - question_score).abs)
  end
  
  def probability_matrix(student)
    matrix = []
    questions.each do |question|
      question_score = question.skill
      student_score = StudentSkill.where(student_id: student.id, standard_id: question.standard.id).first.skill
      n = probability(student_score,question_score)
      n.times do
        matrix << question.id
      end
    end
    matrix
  end
  
  def unique_select(matrix, n)
    unique_values = []
    n.times do
      idx = rand(matrix.length)
      unique_values << matrix[idx]
      matrix.delete(matrix[idx])
    end
    unique_values = unique_values.shuffle
    unique_values
  end
      
end

app/controllers/exams_controller.rb
class ExamsController < ApplicationController
  before_action :correct_user
  
  def index
    @course = Course.find_by(id: params[:course_id])
  end
  
  def new
    @course = Course.find_by(id: params[:course_id])
  end
    
  def create
    @course = Course.find_by(id: params[:course_id])
    if params[:exam][:name].blank?
      flash.now[:error] = ["Name can't be blank"]
      render 'new'
    else
    params[:exam][:name].split("\n").each do |name|
    @exam = Exam.create({name: name.strip, course_id: params[:course_id]})
    end
   redirect_to user_course_exams_path(user_id: @exam.author.id, course_id: @exam.course.id)
    end
  end
    
    def destroy
      Exam.find_by(id: params[:id]).destroy
      redirect_to user_course_exams_path(user_id: params[:user_id], course_id: params[:course_id])
    end
    
    def edit
      @exam = Exam.find_by(id: params[:exam_id])
    end
    
    def update
    @exam = Exam.find_by(id: params[:id])
    if @exam.update(name: params[:exam][:name])
      redirect_to user_course_exams_path(user_id: current_user.id, course_id: @exam.course.id)
    else
      flash.now[:error] = @exam.errors.full_messages
      render 'edit'
    end
    end
    
    def publish
      @exam = Exam.find_by(id: params[:exam_id])
    end
    
    def scramble
      @exam = Exam.find_by(id: params[:exam_id])
      if @exam.questions.count < params[:publish][:number_of_questions].to_i
        flash[:alert] = "Desired number of questions cannot exceed available questions!"
        redirect_to publish_user_course_exam_path(user_id: current_user.id, course: @exam.course.id, id: @exam.id)
      else
      exam_name = @exam.name
      course_name = @exam.course.name
      school_name = @exam.author.school
      student_exams = @exam.scramble(params[:publish][:who],params[:publish][:number_of_questions])
      respond_to do |format|
        
        format.pdf do
          pdf = Prawn::Document.new
          student_exams.each do |student_exam|
        
          student = Student.find_by(id: student_exam[0])
          student_name = student.name
          section_name = student.section.name
        
          pdf.text student_name + ', ' + section_name
          pdf.text course_name + ', ' + school_name
          pdf.move_down 20
          pdf.text exam_name, :align => :center 
          pdf.move_down 20
        
          queries = student_exam[1]
          queries.each_with_index do |query, idx|
            n = idx + 1
            query_text = n.to_s + '. ' + Question.find_by(id: query).body
            pdf.text query_text
            pdf.move_down 100
          end
          
          pdf.start_new_page
          
          end
      
          if params[:publish][:answer_key].to_i == 1
            student_exams.each do |student_exam|
          
            student = Student.find_by(id: student_exam[0])
            student_name = student.name
            section_name = student.section.name
          
            pdf.text student_name + ', ' + section_name
            pdf.text course_name + ', ' + school_name
            pdf.move_down 20
            pdf.text exam_name + " Answer Key", :align => :center
            pdf.move_down 20
        
            queries = student_exam[1]
            queries.each_with_index do |query, idx|
              n = idx + 1
              answer_text = n.to_s + '. ' + Question.find_by(id: query).answer
              pdf.text answer_text
              pdf.move_down 10
            end
            pdf.start_new_page
            end
          end
        send_data pdf.render,
        filename: "#{exam_name}.pdf",
        type: 'application/pdf',
        disposition: 'inline'
      end
    end
      end
    end
end

      

app/helpers/exams_helper.rb
module ExamsHelper
end

app/views/exams/edit.html.erb
<%= render "shared/edit", {obj: :exam, url: user_course_exam_path(user_id: current_user.id, course_id: @exam.course.id, id: @exam.id)} %>

<br></br>

<%= link_to "Return", user_course_exams_path(user_id: current_user.id, course_id: @exam.course.id) %>

app/views/exams/index.html.erb
<h1><%= @course.name %> Exams (<%= link_to "Add Exams", new_user_course_exam_path(user_id: @course.user.id, course_id: @course.id) %>)</h1>

<br>
<% sorted_exams = @course.exams.sort_by {|e| e.name } %>
<% sorted_exams.each do |exam| %>
<h2><%= exam.name %> (<%= link_to "Publish", publish_user_course_exam_path(user_id: @course.user.id, course_id: @course.id, exam_id: exam.id) %>, <%= link_to 'Edit', edit_user_course_exam_path(user_id: exam.author.id, course_id: exam.course.id, id: exam.id ) %>, <%= link_to "Delete", user_course_exam_path(user_id: exam.author.id, course_id: @course.id, id: exam.id), method: :delete %>)</h2>
<h3><%= exam.questions.count %> Questions (<%= link_to "Add Question", new_user_course_exam_question_path(user_id: exam.author.id, course_id: @course.id, exam_id: exam.id) %>)
<% sorted_questions = exam.questions.sort_by {|q| q.name } %>
<% sorted_questions.each do |question| %>
<li> <%= question.name %>: <%= question.question_skill.display %> (<%= link_to 'Edit', edit_user_course_exam_question_path(user_id: question.author.id, course_id: question.course.id, exam_id: exam.id, id: question.id) %>, <%= link_to "Delete", user_course_exam_question_path(user_id: exam.author.id, course_id: @course.id, exam_id: exam.id, id: question.id), method: :delete %>) </li>
<% end %>
</h3>

<br>
<% end %>

<h2><%= link_to "Info", info_path %>, <%= link_to "Return", user_courses_path(user_id: @course.user.id) %></h2>

app/views/exams/new.html.erb
<%= render "shared/form", {obj: :exam, url: user_course_exams_path} %>

<br></br>

<%= link_to "Return", user_course_exams_path(user_id: current_user.id, course_id: @course.id) %>

app/views/exams/publish.html.erb
<h1>Publish <%= @exam.name %></h1>
<h2><%= flash[:alert] %></h2>
<br>
<%= form_for :publish, url: scramble_user_course_exam_path(format: :pdf) do |form| %>
<div><%= form.label :who, 'Recipients' %>
<%= form.select :who, @exam.recipients_hash %><div>
<br>
<div><%= form.label :number_of_questions, 'Desired number of questions' %>
<%= form.number_field :number_of_questions %><div>
<br>
<div><%= form.label :answer_key, 'Publish answer key?' %>
<%= form.check_box :answer_key, checked: true %><div>
<br>
<%= form.submit 'Publish' %>
<% end %>

<br></br>

<%= link_to "Return", user_course_exams_path(user_id: current_user.id, course_id: @exam.course.id) %>